// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetImportMethods() {
  return window['go']['main']['App']['GetImportMethods']();
}

export function Images(arg1) {
  return window['go']['main']['App']['Images'](arg1);
}

export function ImportNewFile() {
  return window['go']['main']['App']['ImportNewFile']();
}

export function ImportProject(arg1, arg2) {
  return window['go']['main']['App']['ImportProject'](arg1, arg2);
}

export function OpenImportFile(arg1, arg2) {
  return window['go']['main']['App']['OpenImportFile'](arg1, arg2);
}

export function Reproject(arg1, arg2, arg3) {
  return window['go']['main']['App']['Reproject'](arg1, arg2, arg3);
}

export function Shortcuts(arg1) {
  return window['go']['main']['App']['Shortcuts'](arg1);
}

export function Triangulate(arg1, arg2) {
  return window['go']['main']['App']['Triangulate'](arg1, arg2);
}
