// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Images(arg1:string):Promise<main.cameraViewer>;

export function Shortcuts(arg1:string):Promise<{[key: string]: string}>;
