// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {photogrammetry} from '../models';

export function Images(arg1:string):Promise<main.cameraViewer>;

export function Reproject(arg1:string,arg2:string,arg3:Array<number>):Promise<photogrammetry.Pos>;

export function Shortcuts(arg1:string):Promise<{[key: string]: photogrammetry.Coordinates}>;

export function Triangulate(arg1:string,arg2:{[key: string]: photogrammetry.Pos}):Promise<Array<number>>;
