// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet() {
  return window['go']['main']['App']['Greet']();
}

export function Images(arg1) {
  return window['go']['main']['App']['Images'](arg1);
}

export function Shortcuts(arg1) {
  return window['go']['main']['App']['Shortcuts'](arg1);
}
