// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {photogrammetry} from '../models';

export function GetImportMethods():Promise<{[key: string]: Array<main.ImportForm>}>;

export function Images(arg1:string):Promise<main.CameraViewer>;

export function ImportNewFile():Promise<string>;

export function ImportProject(arg1:string,arg2:{[key: string]: string}):Promise<string>;

export function OpenImportFile(arg1:string,arg2:number):Promise<string>;

export function Reproject(arg1:string,arg2:string,arg3:Array<number>):Promise<photogrammetry.Pos>;

export function Shortcuts(arg1:string):Promise<{[key: string]: photogrammetry.Coordinates}>;

export function Triangulate(arg1:string,arg2:{[key: string]: photogrammetry.Pos}):Promise<Array<number>>;
